#!/bin/sh
set -eu

cd "$(dirname "$0")/.."

./scripts/verify_platform_v9
./scripts/verify_platform_v10
./scripts/verify_platform_v11
./scripts/verify_platform_v12
./scripts/verify_platform_v13
./scripts/verify_platform_v14
./scripts/verify_platform_v17
